[package]
name = "crowdfunding_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.10"
ic-cdk = "0.12"
ic-cdk-timers = "0.6"
icrc-ledger-types = "0.1.5"
serde = "1.0.197"
serde_derive = "1.0.197"